services:
  postgres:
    container_name: sghu-postgres
    image: postgres:15
    environment:
      POSTGRES_DB: sghu
      POSTGRES_USER: sghu_user
      POSTGRES_PASSWORD: sghu_pass
    ports:
      - "5433:5432"  # Puerto 5433 en host para evitar conflicto con PostgreSQL local
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: sghu-redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:

